# Required
image:
host:

# Optional
clusterIssuer: letsencrypt
containerPort: 80
wwwRedirect: false
changeCause: null
replicas: 1
tls: true
dockerRegistry: null
dockerRegistryAuth: null
restartAfterRedeploy: false
CI_PROJECT_PATH_SLUG:
CI_ENVIRONMENT_SLUG:
containerEnv: {}
# containerEnv:
#   FOO: hello
#   BAR: world
basicAuth: null
